'use strict';
const assert = require('node:assert/strict');
const {AutonomyStore: S} = require('../frontend/app/autonomystore.js');
global.Autonomy = require('../frontend/app/autonomy.js');
const mem = {};
global.localStorage = {getItem:k=>mem[k]||null,setItem:(k,v)=>{mem[k]=v;},removeItem:k=>{delete mem[k];}};
const key='starnet.autonomy.v1';
let server=Autonomy.fresh(), fail=false, malformed=false, hold=null;
const calls=[];
global.fetch=async(url,opts)=>{
  const body=opts.body?JSON.parse(opts.body):null;calls.push(body);
  if(body&&hold)await hold;
  if(body&&fail)return {ok:false,json:async()=>({ok:false,error:'disk full'})};
  if(body&&malformed)return {ok:true,json:async()=>({})};
  if(body)server=Autonomy.normalize(body.posture);
  return {ok:true,json:async()=>({ok:true,summary:Autonomy.summary(server)})};
};
(async()=>{
  mem[key]=JSON.stringify({initiative:'free',reach:'reach',leashPerDay:12});
  await S.init();assert.equal(S.get().initiative,'wait');assert.ok(calls.every(x=>x===null),'boot is read-only');
  assert.equal((await S.applyPreset('build')).ok,true);assert.equal(S.get().initiative,'leash');assert.equal(calls.at(-1).resumeHalt,true);
  assert.equal(JSON.parse(mem[key]).initiative,'leash');
  fail=true;assert.equal((await S.setInitiative('wait')).ok,false);assert.equal(S.get().initiative,'leash');assert.match(S.status().error,/disk full/);
  fail=false;malformed=true;assert.equal((await S.setReach('reach')).ok,false);assert.equal(S.get().reach,'sandbox');malformed=false;
  let release;hold=new Promise(r=>release=r);
  const first=S.setReach('observe'),second=S.setLeash(7);
  await new Promise(r=>setImmediate(r));assert.equal(S.status().pending,true);assert.equal(S.get().reach,'sandbox','pending value is not current');
  release();await Promise.all([first,second]);hold=null;
  assert.equal(server.reach,'observe');assert.equal(server.leashPerDay,7);assert.equal(S.status().pending,false);
  const original=global.fetch;
  global.fetch=async(url,opts)=>{if(opts.body){server=Autonomy.normalize(JSON.parse(opts.body).posture);throw new Error('ack lost');}return original(url,opts);};
  assert.equal((await S.setInitiative('free')).ok,false);assert.equal(S.get().initiative,'free','lost ack reconciles committed state');
  global.fetch=original;
  await S.importState({initiative:'wait',reach:'sandbox',leashPerDay:4});assert.equal(calls.at(-1).resumeHalt,false);
  server={initiative:'leash',reach:'observe',leashPerDay:6};mem[key]='broken';await S.init();assert.equal(S.get().leashPerDay,6,'reload uses server despite missing cache');
  global.fetch=async()=>{throw new Error('offline');};await S.refresh();assert.equal(S.status().loaded,false);assert.match(S.status().error,/offline/);
  global.fetch=original;await S.refresh();assert.equal(S.status().loaded,true);assert.equal(S.status().error,'');
  let emitted=0;global.U={bus:{emit:()=>emitted++}};await S.setLeash(12);assert.equal(emitted,0);
  fail=true;assert.equal((await S.reset()).ok,false);assert.equal(S.get().initiative,server.initiative);
  fail=false;await S.reset();assert.equal(mem[key],undefined);assert.equal(S.get().initiative,'wait');assert.equal(server.initiative,'wait');assert.equal(calls.at(-1).resumeHalt,false);
  console.log('autonomystore.test: PASS (confirmed writes, failures, serialization, lost ack, reload, recovery)');
})().catch(e=>{console.error(e);process.exitCode=1;});
