/* node test/website-app-sync.test.js — website/app must stay a real copy of frontend/.
 *
 * website/app is the live demo embedded on starnetos.com, and demo-boot.js + live-preview.js both
 * describe it as "a verbatim copy of the app frontend". On 2026-07-24 it was not: 59 files differed
 * and 394 were missing, so the public embed advertised retired copy (an "IMPORT AGENT" button the
 * app had renamed to "RESTORE BACKUP", a provider picker with no grok/kimi). A marketing surface
 * that misrepresents the shipped product is a truthfulness bug.
 *
 * The copy is generated by scripts/sync-website-app.mjs. This gate runs its --check mode so a lane
 * that edits frontend/ and forgets to re-sync fails here instead of shipping a stale embed.
 */
'use strict';
const A = require('./_assert.js');
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const SCRIPT = path.join(ROOT, 'scripts', 'sync-website-app.mjs');

const res = spawnSync(process.execPath, [SCRIPT, '--check'], { cwd: ROOT, encoding: 'utf8' });
const out = String(res.stdout || '') + String(res.stderr || '');
A.eq(res.status, 0, 'website/app is in sync with frontend/ — if this fails, run: npm run sync:website\n' + out);

// The three deliberate embed differences must SURVIVE every sync. Each is load-bearing:
const idx = fs.readFileSync(path.join(ROOT, 'website', 'app', 'index.html'), 'utf8');
A.eq(/fonts\.googleapis\.com|fonts\.gstatic\.com/.test(idx), false, 'the public embed makes zero third-party font requests');
A.ok(/<script src="demo-boot\.js\?v=20260922-current-starter-v6"><\/script>/.test(idx),
  'the embed still boots its captured demo save with an explicit cache revision');
A.ok(/<link rel="stylesheet" href="demo\.css\?v=20260921">/.test(idx), 'the embed carries its cache-versioned camera styling');
A.ok(idx.indexOf('demo-boot.js') < idx.indexOf('<script src="app/'), 'demo-boot runs BEFORE the first app script, so the demo save seeds ahead of any store read');
for (const f of ['demo-boot.js', 'demo.css']) {
  A.ok(fs.existsSync(path.join(ROOT, 'website', 'app', f)), 'embed-only file survives the sync: ' + f);
}
// And the embed must not have re-acquired the app's own dev-only seams.
A.eq(fs.existsSync(path.join(ROOT, 'website', 'app', 'app', 'chat.js')), true, 'the embed carries the real app sources, not a stub');

A.report('website-app-sync.test');
